services:
  langfuse-server:
    container_name: langfuse-server
    image: langfuse/langfuse:2
    restart: unless-stopped
    depends_on:
      pg-database:
        condition: service_healthy
    ports:
      - 3002:3000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg-database:5432/${POSTGRES_DB}
      - NEXTAUTH_SECRET=eG1Kc8IE3sjrkAsi
      - SALT=eG1Kc8IE3sjrkAsi
      - NEXTAUTH_URL=http://localhost:3002
      - TELEMETRY_ENABLED=false
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=true
    networks:
      - llm-network

  mongodb-service:
    container_name: mongodb-servicee
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - llm-network
    dns:
      - 8.8.8.8
    restart: "unless-stopped"
    volumes:
      - mongodb_data:/data/db

  pg-database:
    container_name: pg-database
    image: postgres:15
    restart: unless-stopped
    command: -c 'max_connections=1000'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d DEV"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - "postgres_dataa:/var/lib/postgresql/data:rw"
    ports:
      - 5433:5432
    networks:
      - llm-network

  pg-admin:
    container_name: pg-admin
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - 8002:80
    networks:
      - llm-network
    depends_on:
      - pg-database

volumes:
  mongodb_data:
    name: mongodb_data
    external: true

  postgres_dataa:
    name: postgres_dataa
    external: true

  pgadmin_data:
    name: pgadmin_data
    external: true

networks:
  llm-network:
    external: true

