{{- range .Values.services }}
{{- if and .enabled .persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .persistence.size }}
  storageClassName: {{ .persistence.storageClass }}
---
{{- end }}
{{- end }}
