"""enhance_bills_and_transactions_with_detailed_fields

Revision ID: 648c28bbe87e
Revises: c25badf3cc9c
Create Date: 2025-07-04 11:33:17.960649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648c28bbe87e'
down_revision: Union[str, None] = 'c25badf3cc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('vendor_address', sa.Text(), nullable=True))
    op.add_column('bills', sa.Column('vendor_contact', sa.String(), nullable=True))
    op.add_column('bills', sa.Column('recipient_name', sa.String(), nullable=True))
    op.add_column('bills', sa.Column('recipient_address', sa.Text(), nullable=True))
    op.add_column('bills', sa.Column('document_date', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('bills', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('period_from', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('period_to', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('bills', sa.Column('payment_terms', sa.Text(), nullable=True))
    op.add_column('bills', sa.Column('previous_balance', sa.Float(), nullable=True))
    op.create_index(op.f('ix_bills_recipient_name'), 'bills', ['recipient_name'], unique=False)
    op.add_column('transactions', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('table_section', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.alter_column('transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'table_section')
    op.drop_column('transactions', 'category')
    op.drop_column('transactions', 'transaction_date')
    op.drop_index(op.f('ix_bills_recipient_name'), table_name='bills')
    op.drop_column('bills', 'previous_balance')
    op.drop_column('bills', 'payment_terms')
    op.drop_column('bills', 'currency')
    op.drop_column('bills', 'period_to')
    op.drop_column('bills', 'period_from')
    op.drop_column('bills', 'due_date')
    op.drop_column('bills', 'document_type')
    op.drop_column('bills', 'document_date')
    op.drop_column('bills', 'recipient_address')
    op.drop_column('bills', 'recipient_name')
    op.drop_column('bills', 'vendor_contact')
    op.drop_column('bills', 'vendor_address')
    # ### end Alembic commands ###
