"""Initialize db models

Revision ID: 239b3b78d573
Revises: 635d9283a785
Create Date: 2025-01-11 20:02:49.515490

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "239b3b78d573"
down_revision: Union[str, None] = "635d9283a785"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(length=2000), type_=sa.String(length=200), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=sa.String(length=200), type_=sa.VARCHAR(length=2000), existing_nullable=True)
    # ### end Alembic commands ###
