name: Build and Deploy - DEV
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  init_job:
    runs-on: ubuntu-latest
    steps:
      - name: dev_deploy
        run: echo "dev here"

  fetch_latest_changes:
    runs-on: ubuntu-latest
    needs: init_job
    steps:
      - name: Fetch latest changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          with: 
            REPO_PATH_DEV: ${{ env.REPO_PATH_DEV }}
          script: |
            echo "Starting DEV deployment.."
            cd ${REPO_PATH_DEV }
            ./deploy.sh fetch_latest_changes main

  build_deploy:
    runs-on: ubuntu-latest
    needs: fetch_latest_changes
    steps:
      - name: Build docker containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            echo "Starting DEV deployment build.."
            cd ${{ env.REPO_PATH_DEV }}
            ./deploy.sh deploy_ci main
    
  health_checks:
    runs-on: ubuntu-latest
    needs: build_deploy
    steps:  
    - name: Perform health checks
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ${{ secrets.USERNAME_DEV }}
        key: ${{ secrets.SSH_KEY_DEV }}
        script: |
          docker ps 
          
          echo "Sleeping for 20 seconds until containers are up.."
          sleep 20

          BACKEND_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8082/api/health)

          if [ $BACKEND_CODE != 200 ] 
          then
              echo "FAILURE with status $BACKEND_CODE, backend not reachable"
              exit 1
          fi

          FRONTEND_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3001)

          if [ $FRONTEND_CODE != 200 ] 
          then
              echo "FAILURE with status $FRONTEND_CODE, frontend not reachable"
              exit 1
          fi