name: Build and Deploy - PROD

on:
  workflow_dispatch:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:


  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache pre-commit hooks
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          cd ./bot_service/src/backend/
          pip3 install pre-commit
          pre-commit install

      - name: Run pre-commit
        run: |
          cd ./bot_service/src/backend/
          pre-commit run -a

  run_tests:
    runs-on: ubuntu-latest
    # needs: precommit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --disable-pip-version-check --no-cache-dir --no-input uv
          uv venv
          uv pip install --no-cache -r bot_service/src/backend/requirements.in
          source ./.venv/bin/activate
          pip3 install pytest

      - name: Run tests
        run: |
          source ./.venv/bin/activate
          pytest -v ./bot_service/src/backend/tests/

  fetch_latest_changes:
    runs-on: ubuntu-latest
    needs: [run_tests, precommit]
    if: github.event_name == 'push'
    steps:
      - name: Fetch latest changes
        uses: appleboy/ssh-action@v1.0.3
        env:
          REPO_PATH_PROD: ${{ secrets.REPO_PATH_PROD }}
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          script: |
            echo "Starting PROD deployment.."
            cd ${{ secrets.REPO_PATH_PROD }}
            ./deploy.sh fetch_latest_changes ${{ secrets.PROD_BRANCH }}

  build_deploy:
    runs-on: ubuntu-latest
    needs: fetch_latest_changes
    if: github.event_name == 'push'
    steps:
      - name: Build docker containers
        uses: appleboy/ssh-action@v1.0.3
        env:
          REPO_PATH_PROD: ${{ secrets.REPO_PATH_PROD }}
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          script: |
            echo "Starting PROD deployment build.."
            cd ${{ secrets.REPO_PATH_PROD }}
            ./deploy.sh deploy_ci main

  health_checks:
    runs-on: ubuntu-latest
    needs: build_deploy
    if: github.event_name == 'push'
    steps:
      - name: Perform health checks
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          script: |
            docker ps

            echo "Sleeping for 20 seconds until containers are up.."
            sleep 20

            BACKEND_CODE=$(curl -s -o /PROD/null -w "%{http_code}" http://localhost:8082/api/v1/health)
            # FRONTEND_CODE=$(curl -s -o /PROD/null -w "%{http_code}" http://localhost:3001)

            if [ $BACKEND_CODE != 200 ]
            then
                echo "FAILURE with status $BACKEND_CODE, backend not reachable"
                exit 1
            fi

            if [ $FRONTEND_CODE != 200 ]
            then
                echo "FAILURE with status $FRONTEND_CODE, frontend not reachable"
                exit 1
            fi
